services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flyup-api-dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: air

  db:
    image: postgres:18
    container_name: flyup-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flyup
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d flyup"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: