services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /etc/flyup/.env:/app/.env:ro
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flyup
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d flyup" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: