FROM golang:1.25-alpine

WORKDIR /app

# install git
RUN apk add --no-cache git

# install air (hot reload)
RUN go install github.com/air-verse/air@latest

# copy go mod ก่อน (cache dependency)
COPY go.mod go.sum ./
RUN go mod download

# copy source
COPY . .

EXPOSE 3000

CMD ["air"]