// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	domain "flyup/internal/domain"
	dto "flyup/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

// CloseMeetingsByMilestoneID provides a mock function with given fields: milestoneID
func (_m *MockProjectRepository) CloseMeetingsByMilestoneID(milestoneID uint) error {
	ret := _m.Called(milestoneID)

	if len(ret) == 0 {
		panic("no return value specified for CloseMeetingsByMilestoneID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(milestoneID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountMilestoneVotes provides a mock function with given fields: milestoneID, choice
func (_m *MockProjectRepository) CountMilestoneVotes(milestoneID uint, choice domain.MilestoneVoteChoice) (int64, error) {
	ret := _m.Called(milestoneID, choice)

	if len(ret) == 0 {
		panic("no return value specified for CountMilestoneVotes")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.MilestoneVoteChoice) (int64, error)); ok {
		return rf(milestoneID, choice)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.MilestoneVoteChoice) int64); ok {
		r0 = rf(milestoneID, choice)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint, domain.MilestoneVoteChoice) error); ok {
		r1 = rf(milestoneID, choice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountFundedProjects provides a mock function with given fields:
func (_m *MockProjectRepository) CountFundedProjects() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountFundedProjects")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountPassedMilestones provides a mock function with given fields:
func (_m *MockProjectRepository) CountPassedMilestones() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountPassedMilestones")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountProjectsByCategoryID provides a mock function with given fields: categoryID
func (_m *MockProjectRepository) CountProjectsByCategoryID(categoryID uint) (int64, error) {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for CountProjectsByCategoryID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (int64, error)); ok {
		return rf(categoryID)
	}
	if rf, ok := ret.Get(0).(func(uint) int64); ok {
		r0 = rf(categoryID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountVerifiedBoostersByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) CountVerifiedBoostersByProjectID(projectID uint) (int64, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for CountVerifiedBoostersByProjectID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (int64, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) int64); ok {
		r0 = rf(projectID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCategory provides a mock function with given fields: category
func (_m *MockProjectRepository) CreateCategory(category *domain.ProjectCategory) (*domain.ProjectCategory, error) {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *domain.ProjectCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectCategory) (*domain.ProjectCategory, error)); ok {
		return rf(category)
	}
	if rf, ok := ret.Get(0).(func(*domain.ProjectCategory) *domain.ProjectCategory); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.ProjectCategory) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateFAQ provides a mock function with given fields: faq
func (_m *MockProjectRepository) CreateFAQ(faq *domain.ProjectFAQ) error {
	ret := _m.Called(faq)

	if len(ret) == 0 {
		panic("no return value specified for CreateFAQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectFAQ) error); ok {
		r0 = rf(faq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMilestone provides a mock function with given fields: m
func (_m *MockProjectRepository) CreateMilestone(m *domain.Milestone) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for CreateMilestone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Milestone) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProject provides a mock function with given fields: project
func (_m *MockProjectRepository) CreateProject(project *domain.Project) (*domain.Project, error) {
	ret := _m.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Project) (*domain.Project, error)); ok {
		return rf(project)
	}
	if rf, ok := ret.Get(0).(func(*domain.Project) *domain.Project); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Project) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProjectMedia provides a mock function with given fields: media
func (_m *MockProjectRepository) CreateProjectMedia(media *domain.ProjectMedia) error {
	ret := _m.Called(media)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectMedia) error); ok {
		r0 = rf(media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProjectUpdate provides a mock function with given fields: update
func (_m *MockProjectRepository) CreateProjectUpdate(update *domain.ProjectUpdate) error {
	ret := _m.Called(update)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectUpdate) error); ok {
		r0 = rf(update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateStorySection provides a mock function with given fields: section
func (_m *MockProjectRepository) CreateStorySection(section *domain.StorySection) error {
	ret := _m.Called(section)

	if len(ret) == 0 {
		panic("no return value specified for CreateStorySection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.StorySection) error); ok {
		r0 = rf(section)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateThread provides a mock function with given fields: thread
func (_m *MockProjectRepository) CreateThread(thread *domain.ProjectThread) error {
	ret := _m.Called(thread)

	if len(ret) == 0 {
		panic("no return value specified for CreateThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectThread) error); ok {
		r0 = rf(thread)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateThreadMessage provides a mock function with given fields: msg
func (_m *MockProjectRepository) CreateThreadMessage(msg *domain.ProjectThreadMessage) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateThreadMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectThreadMessage) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCategory provides a mock function with given fields: categoryId
func (_m *MockProjectRepository) DeleteCategory(categoryId uint) error {
	ret := _m.Called(categoryId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(categoryId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFAQ provides a mock function with given fields: faqID
func (_m *MockProjectRepository) DeleteFAQ(faqID uint) error {
	ret := _m.Called(faqID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFAQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(faqID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMilestone provides a mock function with given fields: id
func (_m *MockProjectRepository) DeleteMilestone(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMilestone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProject provides a mock function with given fields: projectId
func (_m *MockProjectRepository) DeleteProject(projectId uint) error {
	ret := _m.Called(projectId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(projectId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProjectMedia provides a mock function with given fields: mediaID
func (_m *MockProjectRepository) DeleteProjectMedia(mediaID uint) error {
	ret := _m.Called(mediaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(mediaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProjectUpdate provides a mock function with given fields: updateID
func (_m *MockProjectRepository) DeleteProjectUpdate(updateID uint) error {
	ret := _m.Called(updateID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(updateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteStorySection provides a mock function with given fields: sectionID
func (_m *MockProjectRepository) DeleteStorySection(sectionID uint) error {
	ret := _m.Called(sectionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStorySection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(sectionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteThread provides a mock function with given fields: threadID
func (_m *MockProjectRepository) DeleteThread(threadID uint) error {
	ret := _m.Called(threadID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteThreadMessage provides a mock function with given fields: msgID
func (_m *MockProjectRepository) DeleteThreadMessage(msgID uint) error {
	ret := _m.Called(msgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteThreadMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(msgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsProjectByOwnerAndStates provides a mock function with given fields: userID, states
func (_m *MockProjectRepository) ExistsProjectByOwnerAndStates(userID uint, states []domain.ProjectState) (bool, error) {
	ret := _m.Called(userID, states)

	if len(ret) == 0 {
		panic("no return value specified for ExistsProjectByOwnerAndStates")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, []domain.ProjectState) (bool, error)); ok {
		return rf(userID, states)
	}
	if rf, ok := ret.Get(0).(func(uint, []domain.ProjectState) bool); ok {
		r0 = rf(userID, states)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint, []domain.ProjectState) error); ok {
		r1 = rf(userID, states)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllCategories provides a mock function with no fields
func (_m *MockProjectRepository) FindAllCategories() ([]domain.ProjectCategory, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllCategories")
	}

	var r0 []domain.ProjectCategory
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ProjectCategory, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ProjectCategory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectCategory)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCategoryByID provides a mock function with given fields: id
func (_m *MockProjectRepository) FindCategoryByID(id uint) (*domain.ProjectCategory, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindCategoryByID")
	}

	var r0 *domain.ProjectCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.ProjectCategory, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.ProjectCategory); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindExecutingProjects provides a mock function with no fields
func (_m *MockProjectRepository) FindExecutingProjects() ([]domain.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindExecutingProjects")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindFAQByID provides a mock function with given fields: faqID
func (_m *MockProjectRepository) FindFAQByID(faqID uint) (*domain.ProjectFAQ, error) {
	ret := _m.Called(faqID)

	if len(ret) == 0 {
		panic("no return value specified for FindFAQByID")
	}

	var r0 *domain.ProjectFAQ
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.ProjectFAQ, error)); ok {
		return rf(faqID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.ProjectFAQ); ok {
		r0 = rf(faqID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectFAQ)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(faqID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindFAQsByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindFAQsByProjectID(projectID uint) ([]domain.ProjectFAQ, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindFAQsByProjectID")
	}

	var r0 []domain.ProjectFAQ
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.ProjectFAQ, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.ProjectFAQ); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectFAQ)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindInvestorIDsByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindInvestorIDsByProjectID(projectID uint) ([]uint, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindInvestorIDsByProjectID")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]uint, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []uint); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindInvestorsEmailByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindInvestorsEmailByProjectID(projectID uint) ([]string, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindInvestorsEmailByProjectID")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]string, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []string); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMediaByID provides a mock function with given fields: id
func (_m *MockProjectRepository) FindMediaByID(id uint) (*domain.ProjectMedia, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindMediaByID")
	}

	var r0 *domain.ProjectMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.ProjectMedia, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.ProjectMedia); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectMedia)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMediaByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindMediaByProjectID(projectID uint) ([]domain.ProjectMedia, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindMediaByProjectID")
	}

	var r0 []domain.ProjectMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.ProjectMedia, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.ProjectMedia); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectMedia)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMeetingByID provides a mock function with given fields: id
func (_m *MockProjectRepository) FindMeetingByID(id uint) (*domain.Meeting, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindMeetingByID")
	}

	var r0 *domain.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Meeting, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Meeting); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMeetingByMilestoneID provides a mock function with given fields: milestoneID
func (_m *MockProjectRepository) FindMeetingByMilestoneID(milestoneID uint) (*domain.Meeting, error) {
	ret := _m.Called(milestoneID)

	if len(ret) == 0 {
		panic("no return value specified for FindMeetingByMilestoneID")
	}

	var r0 *domain.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Meeting, error)); ok {
		return rf(milestoneID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Meeting); ok {
		r0 = rf(milestoneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(milestoneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMeetingsByInvestorID provides a mock function with given fields: investorUserID
func (_m *MockProjectRepository) FindMeetingsByInvestorID(investorUserID uint) ([]domain.Meeting, error) {
	ret := _m.Called(investorUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindMeetingsByInvestorID")
	}

	var r0 []domain.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Meeting, error)); ok {
		return rf(investorUserID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Meeting); ok {
		r0 = rf(investorUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(investorUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMeetingsByMilestone provides a mock function with given fields: milestoneID, filter
func (_m *MockProjectRepository) FindMeetingsByMilestone(milestoneID uint, filter string) ([]domain.Meeting, error) {
	ret := _m.Called(milestoneID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindMeetingsByMilestone")
	}

	var r0 []domain.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) ([]domain.Meeting, error)); ok {
		return rf(milestoneID, filter)
	}
	if rf, ok := ret.Get(0).(func(uint, string) []domain.Meeting); ok {
		r0 = rf(milestoneID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(milestoneID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMeetingsByOwnerID provides a mock function with given fields: ownerID
func (_m *MockProjectRepository) FindMeetingsByOwnerID(ownerID uint) ([]domain.Meeting, error) {
	ret := _m.Called(ownerID)

	if len(ret) == 0 {
		panic("no return value specified for FindMeetingsByOwnerID")
	}

	var r0 []domain.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Meeting, error)); ok {
		return rf(ownerID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Meeting); ok {
		r0 = rf(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMeetingsByProject provides a mock function with given fields: projectID, filter
func (_m *MockProjectRepository) FindMeetingsByProject(projectID uint, filter string) ([]domain.Meeting, error) {
	ret := _m.Called(projectID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindMeetingsByProject")
	}

	var r0 []domain.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) ([]domain.Meeting, error)); ok {
		return rf(projectID, filter)
	}
	if rf, ok := ret.Get(0).(func(uint, string) []domain.Meeting); ok {
		r0 = rf(projectID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(projectID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMessagesByThreadID provides a mock function with given fields: threadID
func (_m *MockProjectRepository) FindMessagesByThreadID(threadID uint) ([]domain.ProjectThreadMessage, error) {
	ret := _m.Called(threadID)

	if len(ret) == 0 {
		panic("no return value specified for FindMessagesByThreadID")
	}

	var r0 []domain.ProjectThreadMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.ProjectThreadMessage, error)); ok {
		return rf(threadID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.ProjectThreadMessage); ok {
		r0 = rf(threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectThreadMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMilestoneByID provides a mock function with given fields: id
func (_m *MockProjectRepository) FindMilestoneByID(id uint) (*domain.Milestone, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindMilestoneByID")
	}

	var r0 *domain.Milestone
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Milestone, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Milestone); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Milestone)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMilestonesByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindMilestonesByProjectID(projectID uint) ([]domain.Milestone, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindMilestonesByProjectID")
	}

	var r0 []domain.Milestone
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Milestone, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Milestone); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Milestone)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMilestonesByProjectIDAndStatus provides a mock function with given fields: projectID, status
func (_m *MockProjectRepository) FindMilestonesByProjectIDAndStatus(projectID uint, status domain.MilestoneStatus) ([]domain.Milestone, error) {
	ret := _m.Called(projectID, status)

	if len(ret) == 0 {
		panic("no return value specified for FindMilestonesByProjectIDAndStatus")
	}

	var r0 []domain.Milestone
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.MilestoneStatus) ([]domain.Milestone, error)); ok {
		return rf(projectID, status)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.MilestoneStatus) []domain.Milestone); ok {
		r0 = rf(projectID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Milestone)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, domain.MilestoneStatus) error); ok {
		r1 = rf(projectID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMilestonesByStatus provides a mock function with given fields: status
func (_m *MockProjectRepository) FindMilestonesByStatus(status domain.MilestoneStatus) ([]domain.Milestone, error) {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for FindMilestonesByStatus")
	}

	var r0 []domain.Milestone
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.MilestoneStatus) ([]domain.Milestone, error)); ok {
		return rf(status)
	}
	if rf, ok := ret.Get(0).(func(domain.MilestoneStatus) []domain.Milestone); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Milestone)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.MilestoneStatus) error); ok {
		r1 = rf(status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNewProjects provides a mock function with no fields
func (_m *MockProjectRepository) FindNewProjects() ([]domain.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindNewProjects")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectByID provides a mock function with given fields: id
func (_m *MockProjectRepository) FindProjectByID(id uint) (*domain.Project, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectByID")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Project, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Project); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectByIDAndOwner provides a mock function with given fields: id, ownerID
func (_m *MockProjectRepository) FindProjectByIDAndOwner(id uint, ownerID uint) (*domain.Project, error) {
	ret := _m.Called(id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectByIDAndOwner")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*domain.Project, error)); ok {
		return rf(id, ownerID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *domain.Project); ok {
		r0 = rf(id, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(id, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectDetailByID provides a mock function with given fields: id, state, status, visibility
func (_m *MockProjectRepository) FindProjectDetailByID(id uint, state *domain.ProjectState, status *domain.ProjectStatus, visibility *domain.ProjectVisibility) (*domain.Project, error) {
	ret := _m.Called(id, state, status, visibility)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectDetailByID")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, *domain.ProjectState, *domain.ProjectStatus, *domain.ProjectVisibility) (*domain.Project, error)); ok {
		return rf(id, state, status, visibility)
	}
	if rf, ok := ret.Get(0).(func(uint, *domain.ProjectState, *domain.ProjectStatus, *domain.ProjectVisibility) *domain.Project); ok {
		r0 = rf(id, state, status, visibility)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, *domain.ProjectState, *domain.ProjectStatus, *domain.ProjectVisibility) error); ok {
		r1 = rf(id, state, status, visibility)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectEndingSoon provides a mock function with no fields
func (_m *MockProjectRepository) FindProjectEndingSoon() ([]domain.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindProjectEndingSoon")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectRecommendations provides a mock function with no fields
func (_m *MockProjectRepository) FindProjectRecommendations() ([]domain.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindProjectRecommendations")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectUpdateByID provides a mock function with given fields: updateID
func (_m *MockProjectRepository) FindProjectUpdateByID(updateID uint) (*domain.ProjectUpdate, error) {
	ret := _m.Called(updateID)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectUpdateByID")
	}

	var r0 *domain.ProjectUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.ProjectUpdate, error)); ok {
		return rf(updateID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.ProjectUpdate); ok {
		r0 = rf(updateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(updateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjects provides a mock function with given fields: state, status, visibility, categoryID, search
func (_m *MockProjectRepository) FindProjects(state *domain.ProjectState, status *domain.ProjectStatus, visibility *domain.ProjectVisibility, categoryID *uint, search string) ([]domain.Project, error) {
	ret := _m.Called(state, status, visibility, categoryID, search)

	if len(ret) == 0 {
		panic("no return value specified for FindProjects")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectState, *domain.ProjectStatus, *domain.ProjectVisibility, *uint, string) ([]domain.Project, error)); ok {
		return rf(state, status, visibility, categoryID, search)
	}
	if rf, ok := ret.Get(0).(func(*domain.ProjectState, *domain.ProjectStatus, *domain.ProjectVisibility, *uint, string) []domain.Project); ok {
		r0 = rf(state, status, visibility, categoryID, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.ProjectState, *domain.ProjectStatus, *domain.ProjectVisibility, *uint, string) error); ok {
		r1 = rf(state, status, visibility, categoryID, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectsByCategory provides a mock function with given fields: categoryID
func (_m *MockProjectRepository) FindProjectsByCategory(categoryID uint) ([]domain.Project, error) {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectsByCategory")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Project, error)); ok {
		return rf(categoryID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Project); ok {
		r0 = rf(categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectsByOwnerID provides a mock function with given fields: ownerID
func (_m *MockProjectRepository) FindProjectsByOwnerID(ownerID uint) ([]domain.Project, error) {
	ret := _m.Called(ownerID)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectsByOwnerID")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Project, error)); ok {
		return rf(ownerID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Project); ok {
		r0 = rf(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectsCancelRequest provides a mock function with no fields
func (_m *MockProjectRepository) FindProjectsCancelRequest() ([]domain.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindProjectsCancelRequest")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectsPendingDetail provides a mock function with given fields: projectID, state
func (_m *MockProjectRepository) FindProjectsPendingDetail(projectID uint, state string) (*domain.Project, error) {
	ret := _m.Called(projectID, state)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectsPendingDetail")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) (*domain.Project, error)); ok {
		return rf(projectID, state)
	}
	if rf, ok := ret.Get(0).(func(uint, string) *domain.Project); ok {
		r0 = rf(projectID, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(projectID, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProjectsState provides a mock function with given fields: state
func (_m *MockProjectRepository) FindProjectsState(state string) ([]domain.Project, error) {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectsState")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Project, error)); ok {
		return rf(state)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Project); ok {
		r0 = rf(state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPublicProjects provides a mock function with given fields: filter
func (_m *MockProjectRepository) FindPublicProjects(filter dto.PublicProjectFilter) ([]domain.Project, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for FindPublicProjects")
	}

	var r0 []domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.PublicProjectFilter) ([]domain.Project, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(dto.PublicProjectFilter) []domain.Project); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.PublicProjectFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStoriesByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindStoriesByProjectID(projectID uint) ([]domain.StorySection, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindStoriesByProjectID")
	}

	var r0 []domain.StorySection
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.StorySection, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.StorySection); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StorySection)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStorySectionByID provides a mock function with given fields: sectionID
func (_m *MockProjectRepository) FindStorySectionByID(sectionID uint) (*domain.StorySection, error) {
	ret := _m.Called(sectionID)

	if len(ret) == 0 {
		panic("no return value specified for FindStorySectionByID")
	}

	var r0 *domain.StorySection
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.StorySection, error)); ok {
		return rf(sectionID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.StorySection); ok {
		r0 = rf(sectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StorySection)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(sectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindThreadByID provides a mock function with given fields: threadID
func (_m *MockProjectRepository) FindThreadByID(threadID uint) (*domain.ProjectThread, error) {
	ret := _m.Called(threadID)

	if len(ret) == 0 {
		panic("no return value specified for FindThreadByID")
	}

	var r0 *domain.ProjectThread
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.ProjectThread, error)); ok {
		return rf(threadID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.ProjectThread); ok {
		r0 = rf(threadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectThread)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindThreadMessageByID provides a mock function with given fields: msgID
func (_m *MockProjectRepository) FindThreadMessageByID(msgID uint) (*domain.ProjectThreadMessage, error) {
	ret := _m.Called(msgID)

	if len(ret) == 0 {
		panic("no return value specified for FindThreadMessageByID")
	}

	var r0 *domain.ProjectThreadMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.ProjectThreadMessage, error)); ok {
		return rf(msgID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.ProjectThreadMessage); ok {
		r0 = rf(msgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectThreadMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(msgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindThreadsByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindThreadsByProjectID(projectID uint) ([]domain.ProjectThread, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindThreadsByProjectID")
	}

	var r0 []domain.ProjectThread
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.ProjectThread, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.ProjectThread); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectThread)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindThreadsByUpdateID provides a mock function with given fields: projectID, updateID
func (_m *MockProjectRepository) FindThreadsByUpdateID(projectID uint, updateID uint) ([]domain.ProjectThread, error) {
	ret := _m.Called(projectID, updateID)

	if len(ret) == 0 {
		panic("no return value specified for FindThreadsByUpdateID")
	}

	var r0 []domain.ProjectThread
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) ([]domain.ProjectThread, error)); ok {
		return rf(projectID, updateID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) []domain.ProjectThread); ok {
		r0 = rf(projectID, updateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectThread)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(projectID, updateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUpdatesByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) FindUpdatesByProjectID(projectID uint) ([]domain.ProjectUpdate, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindUpdatesByProjectID")
	}

	var r0 []domain.ProjectUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.ProjectUpdate, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.ProjectUpdate); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindVote provides a mock function with given fields: milestoneID, boosterUserID
func (_m *MockProjectRepository) FindVote(milestoneID uint, boosterUserID uint) (*domain.MilestoneVote, error) {
	ret := _m.Called(milestoneID, boosterUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindVote")
	}

	var r0 *domain.MilestoneVote
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*domain.MilestoneVote, error)); ok {
		return rf(milestoneID, boosterUserID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *domain.MilestoneVote); ok {
		r0 = rf(milestoneID, boosterUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MilestoneVote)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(milestoneID, boosterUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApprovedIdCard provides a mock function with given fields: userID
func (_m *MockProjectRepository) GetApprovedIdCard(userID uint) (*domain.IdCardVerification, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetApprovedIdCard")
	}

	var r0 *domain.IdCardVerification
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.IdCardVerification, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.IdCardVerification); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IdCardVerification)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApprovedStudentCard provides a mock function with given fields: userID
func (_m *MockProjectRepository) GetApprovedStudentCard(userID uint) (*domain.StudentCardVerification, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetApprovedStudentCard")
	}

	var r0 *domain.StudentCardVerification
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.StudentCardVerification, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.StudentCardVerification); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentCardVerification)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasCompletedMeeting provides a mock function with given fields: milestoneID
func (_m *MockProjectRepository) HasCompletedMeeting(milestoneID uint) (bool, error) {
	ret := _m.Called(milestoneID)

	if len(ret) == 0 {
		panic("no return value specified for HasCompletedMeeting")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return rf(milestoneID)
	}
	if rf, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = rf(milestoneID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(milestoneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasVerifiedInvestment provides a mock function with given fields: projectID, boosterUserID
func (_m *MockProjectRepository) HasVerifiedInvestment(projectID uint, boosterUserID uint) (bool, error) {
	ret := _m.Called(projectID, boosterUserID)

	if len(ret) == 0 {
		panic("no return value specified for HasVerifiedInvestment")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (bool, error)); ok {
		return rf(projectID, boosterUserID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = rf(projectID, boosterUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(projectID, boosterUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVotesByMilestoneID provides a mock function with given fields: milestoneID
func (_m *MockProjectRepository) ListVotesByMilestoneID(milestoneID uint) ([]domain.MilestoneVote, error) {
	ret := _m.Called(milestoneID)

	if len(ret) == 0 {
		panic("no return value specified for ListVotesByMilestoneID")
	}

	var r0 []domain.MilestoneVote
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.MilestoneVote, error)); ok {
		return rf(milestoneID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.MilestoneVote); ok {
		r0 = rf(milestoneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MilestoneVote)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(milestoneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteVotesByMilestoneID provides a mock function with given fields: milestoneID
func (_m *MockProjectRepository) DeleteVotesByMilestoneID(milestoneID uint) error {
	ret := _m.Called(milestoneID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVotesByMilestoneID")
	}

	if rf, ok := ret.Get(0).(func(uint) error); ok {
		return rf(milestoneID)
	}
	return ret.Error(0)
}

// SaveMeeting provides a mock function with given fields: meeting
func (_m *MockProjectRepository) SaveMeeting(meeting *domain.Meeting) error {
	ret := _m.Called(meeting)

	if len(ret) == 0 {
		panic("no return value specified for SaveMeeting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Meeting) error); ok {
		r0 = rf(meeting)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SumMilestoneVotes provides a mock function with given fields: milestoneID, choice
func (_m *MockProjectRepository) SumMilestoneVotes(milestoneID uint, choice domain.MilestoneVoteChoice) (float64, error) {
	ret := _m.Called(milestoneID, choice)

	if len(ret) == 0 {
		panic("no return value specified for SumMilestoneVotes")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.MilestoneVoteChoice) (float64, error)); ok {
		return rf(milestoneID, choice)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.MilestoneVoteChoice) float64); ok {
		r0 = rf(milestoneID, choice)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uint, domain.MilestoneVoteChoice) error); ok {
		r1 = rf(milestoneID, choice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SumVerifiedInvestmentByProjectID provides a mock function with given fields: projectID
func (_m *MockProjectRepository) SumVerifiedInvestmentByProjectID(projectID uint) (float64, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for SumVerifiedInvestmentByProjectID")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (float64, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) float64); ok {
		r0 = rf(projectID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: category
func (_m *MockProjectRepository) UpdateCategory(category *domain.ProjectCategory) (*domain.ProjectCategory, error) {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *domain.ProjectCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectCategory) (*domain.ProjectCategory, error)); ok {
		return rf(category)
	}
	if rf, ok := ret.Get(0).(func(*domain.ProjectCategory) *domain.ProjectCategory); ok {
		r0 = rf(category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.ProjectCategory) error); ok {
		r1 = rf(category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFAQ provides a mock function with given fields: faq
func (_m *MockProjectRepository) UpdateFAQ(faq *domain.ProjectFAQ) error {
	ret := _m.Called(faq)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFAQ")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectFAQ) error); ok {
		r0 = rf(faq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMeeting provides a mock function with given fields: meeting
func (_m *MockProjectRepository) UpdateMeeting(meeting *domain.Meeting) (*domain.Meeting, error) {
	ret := _m.Called(meeting)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMeeting")
	}

	var r0 *domain.Meeting
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Meeting) (*domain.Meeting, error)); ok {
		return rf(meeting)
	}
	if rf, ok := ret.Get(0).(func(*domain.Meeting) *domain.Meeting); ok {
		r0 = rf(meeting)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Meeting)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Meeting) error); ok {
		r1 = rf(meeting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMilestone provides a mock function with given fields: m
func (_m *MockProjectRepository) UpdateMilestone(m *domain.Milestone) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMilestone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Milestone) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProject provides a mock function with given fields: project
func (_m *MockProjectRepository) UpdateProject(project *domain.Project) (*domain.Project, error) {
	ret := _m.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Project) (*domain.Project, error)); ok {
		return rf(project)
	}
	if rf, ok := ret.Get(0).(func(*domain.Project) *domain.Project); ok {
		r0 = rf(project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Project) error); ok {
		r1 = rf(project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProjectMedia provides a mock function with given fields: media
func (_m *MockProjectRepository) UpdateProjectMedia(media *domain.ProjectMedia) error {
	ret := _m.Called(media)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProjectMedia")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectMedia) error); ok {
		r0 = rf(media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProjectUpdate provides a mock function with given fields: update
func (_m *MockProjectRepository) UpdateProjectUpdate(update *domain.ProjectUpdate) error {
	ret := _m.Called(update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProjectUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectUpdate) error); ok {
		r0 = rf(update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStorySection provides a mock function with given fields: section
func (_m *MockProjectRepository) UpdateStorySection(section *domain.StorySection) error {
	ret := _m.Called(section)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStorySection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.StorySection) error); ok {
		r0 = rf(section)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateThread provides a mock function with given fields: thread
func (_m *MockProjectRepository) UpdateThread(thread *domain.ProjectThread) error {
	ret := _m.Called(thread)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThread")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectThread) error); ok {
		r0 = rf(thread)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateThreadMessage provides a mock function with given fields: msg
func (_m *MockProjectRepository) UpdateThreadMessage(msg *domain.ProjectThreadMessage) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThreadMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProjectThreadMessage) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertMilestoneVote provides a mock function with given fields: vote
func (_m *MockProjectRepository) UpsertMilestoneVote(vote *domain.MilestoneVote) error {
	ret := _m.Called(vote)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMilestoneVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MilestoneVote) error); ok {
		r0 = rf(vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
