// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	domain "flyup/internal/domain"
	dto "flyup/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockInvestmentRepository is an autogenerated mock type for the InvestmentRepository type
type MockInvestmentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: investment
func (_m *MockInvestmentRepository) Create(investment *domain.Investment) error {
	ret := _m.Called(investment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Investment) error); ok {
		r0 = rf(investment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *MockInvestmentRepository) FindByID(id uint) (*domain.Investment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Investment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Investment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Investment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Investment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIDWithProject provides a mock function with given fields: id
func (_m *MockInvestmentRepository) FindByIDWithProject(id uint) (*domain.Investment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithProject")
	}

	var r0 *domain.Investment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Investment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Investment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Investment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByReferenceNumber provides a mock function with given fields: ref
func (_m *MockInvestmentRepository) FindByReferenceNumber(ref string) (*domain.Investment, error) {
	ret := _m.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for FindByReferenceNumber")
	}

	var r0 *domain.Investment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Investment, error)); ok {
		return rf(ref)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Investment); ok {
		r0 = rf(ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Investment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindVerifiedByProjectID provides a mock function with given fields: projectID
func (_m *MockInvestmentRepository) FindVerifiedByProjectID(projectID uint) ([]domain.Investment, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for FindVerifiedByProjectID")
	}

	var r0 []domain.Investment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Investment, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Investment); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Investment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementProjectFunding provides a mock function with given fields: projectID, amount
func (_m *MockInvestmentRepository) IncrementProjectFunding(projectID uint, amount float64) error {
	ret := _m.Called(projectID, amount)

	if len(ret) == 0 {
		panic("no return value specified for IncrementProjectFunding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, float64) error); ok {
		r0 = rf(projectID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByBoosterUserID provides a mock function with given fields: boosterUserID
func (_m *MockInvestmentRepository) ListByBoosterUserID(boosterUserID uint) ([]domain.Investment, error) {
	ret := _m.Called(boosterUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListByBoosterUserID")
	}

	var r0 []domain.Investment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Investment, error)); ok {
		return rf(boosterUserID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Investment); ok {
		r0 = rf(boosterUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Investment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(boosterUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListInvestedProjectsByUserID provides a mock function with given fields: boosterUserID
func (_m *MockInvestmentRepository) ListInvestedProjectsByUserID(boosterUserID uint) ([]dto.InvestedProjectItem, error) {
	ret := _m.Called(boosterUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListInvestedProjectsByUserID")
	}

	var r0 []dto.InvestedProjectItem
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dto.InvestedProjectItem, error)); ok {
		return rf(boosterUserID)
	}
	if rf, ok := ret.Get(0).(func(uint) []dto.InvestedProjectItem); ok {
		r0 = rf(boosterUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.InvestedProjectItem)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(boosterUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListInvestorsByProjectID provides a mock function with given fields: projectID
func (_m *MockInvestmentRepository) ListInvestorsByProjectID(projectID uint) ([]dto.ProjectInvestorItem, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListInvestorsByProjectID")
	}

	var r0 []dto.ProjectInvestorItem
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dto.ProjectInvestorItem, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) []dto.ProjectInvestorItem); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProjectInvestorItem)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRefundPending provides a mock function with no fields
func (_m *MockInvestmentRepository) ListRefundPending() ([]domain.Investment, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListRefundPending")
	}

	var r0 []domain.Investment
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Investment, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Investment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Investment)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SumActiveByProjectID provides a mock function with given fields: projectID
func (_m *MockInvestmentRepository) SumActiveByProjectID(projectID uint) (float64, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for SumActiveByProjectID")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (float64, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(uint) float64); ok {
		r0 = rf(projectID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePaid provides a mock function with given fields: investment
func (_m *MockInvestmentRepository) UpdatePaid(investment *domain.Investment) error {
	ret := _m.Called(investment)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Investment) error); ok {
		r0 = rf(investment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRefunded provides a mock function with given fields: investment
func (_m *MockInvestmentRepository) UpdateRefunded(investment *domain.Investment) error {
	ret := _m.Called(investment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefunded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Investment) error); ok {
		r0 = rf(investment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *MockInvestmentRepository) UpdateStatus(id uint, status domain.InvestmentStatus) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, domain.InvestmentStatus) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockInvestmentRepository creates a new instance of MockInvestmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvestmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvestmentRepository {
	mock := &MockInvestmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
